version: '3'
services:
    my-service:
      image: nstn/crypto
      environment:
      - HTTP_PROXY="http://127.0.0.1:2334"
      - HTTPS_PROXY="http://127.0.0.1:2334"
    api:
      build: .
      depends_on:
        - postgres

      ports:
          - 8000:8000
      volumes:
          - ./:/usr/src/cryp:ro #bind mount
      command: uvicorn cryp.appss:app  --host 0.0.0.0 --port 8000 --reload  
      environment:
         -  DATABASE_HOSTNAME=postgres
         -  DATABASE_PORT=5432
         -  DATABASE_PASSWORD=password123
         -  DATABASE_NAME=cryptocurrency
         -  DATABASE_USERNAME=postgres
         -  SECRET_KEY=wFA8m1l7-fahDuAAQhDa2p0T4XveLo8fl72lpz189FQ
         -  ALGORITHM=HS256
         -  ACCESS_TOKEN_EXPIRE_MINUTES=30
    postgres:
            image: postgres
            environment:
                
                - POSTGRES_PASSWORD=password123
                - POSTGRES_DB=cryptocurrency
            volumes:
                - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db:

