# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createuser.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Create_User(object):
    def setupUi(self, Create_User):
        Create_User.setObjectName("Create_User")
        Create_User.resize(382, 350)
        Create_User.setStyleSheet("QWidget {  \n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,   \n"
"                                 stop:0 #7ed8e0, stop:1 #e0f7fa);  \n"
"    color: #333;  \n"
"    font-family: Arial, sans-serif;  \n"
"}  ")
        self.centralwidget = QtWidgets.QWidget(Create_User)
        self.centralwidget.setObjectName("centralwidget")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(110, 50, 201, 51))
        self.email.setStyleSheet("QLineEdit {  \n"
"    border: 2px solid #00796b; /* Border color */  \n"
"    border-radius: 10px;  \n"
"    padding: 10px;  \n"
"    font-size: 16px; /* Text size */  \n"
"    background-color: #ffffff; /* White background */  \n"
"}  ")
        self.email.setObjectName("email")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(29, 89, 255);\n"
"background-color:transparent;")
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(110, 120, 201, 51))
        self.password.setStyleSheet("QLineEdit {  \n"
"    border: 2px solid #00796b; /* Border color */  \n"
"    border-radius: 10px;  \n"
"    padding: 10px;  \n"
"    font-size: 16px; /* Text size */  \n"
"    background-color: #ffffff; /* White background */  \n"
"}  ")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.repassword = QtWidgets.QLineEdit(self.centralwidget)
        self.repassword.setGeometry(QtCore.QRect(110, 190, 201, 51))
        self.repassword.setStyleSheet("QLineEdit {  \n"
"    border: 2px solid #00796b; /* Border color */  \n"
"    border-radius: 10px;  \n"
"    padding: 10px;  \n"
"    font-size: 16px; /* Text size */  \n"
"    background-color: #ffffff; /* White background */  \n"
"}  ")
        self.repassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repassword.setObjectName("repassword")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("color: rgb(29, 89, 255);\n"
"background-color:transparent;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(29, 89, 255);\n"
"background-color: transparent;")
        self.label_5.setObjectName("label_5")
        self.confirm = QtWidgets.QPushButton(self.centralwidget)
        self.confirm.setGeometry(QtCore.QRect(220, 260, 91, 31))
        self.confirm.setStyleSheet("QPushButton {  \n"
"    background-color: #009688; /* Teal */  \n"
"    color: white; /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    background-color: #00796b; /* Darker teal on hover */  \n"
"}  ")
        self.confirm.setObjectName("confirm")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(29, 89, 255);\n"
"background-color:transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        Create_User.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Create_User)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 382, 23))
        self.menubar.setObjectName("menubar")
        Create_User.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Create_User)
        self.statusbar.setObjectName("statusbar")
        Create_User.setStatusBar(self.statusbar)

        self.retranslateUi(Create_User)
        QtCore.QMetaObject.connectSlotsByName(Create_User)

    def retranslateUi(self, Create_User):
        _translate = QtCore.QCoreApplication.translate
        Create_User.setWindowTitle(_translate("Create_User", "creteuser"))
        self.label.setText(_translate("Create_User", "Eamil Address"))
        self.label_4.setText(_translate("Create_User", "Password"))
        self.label_5.setText(_translate("Create_User", "Confirm pass"))
        self.confirm.setText(_translate("Create_User", "Confirm"))
        self.label_2.setText(_translate("Create_User", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Create_User = QtWidgets.QMainWindow()
    ui = Ui_Create_User()
    ui.setupUi(Create_User)
    Create_User.show()
    sys.exit(app.exec_())
