# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_crypto.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Crypto(object):
    def setupUi(self, Form_Crypto):
        Form_Crypto.setObjectName("Form_Crypto")
        Form_Crypto.resize(1033, 924)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_Crypto.sizePolicy().hasHeightForWidth())
        Form_Crypto.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../icon/gno.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form_Crypto.setWindowIcon(icon)
        Form_Crypto.setStyleSheet("QScrollBar:vertical {  \n"
"    background-color:rgb(139, 211, 217) ;            /* Background color */  \n"
"    width: 14px;                    /* Width of the scrollbar */  \n"
"    border:none;  \n"
"    border-radius: 0px;\n"
"        /* Border styling */  \n"
"}  \n"
"\n"
"QScrollBar::handle:vertical {  \n"
"    background-color:rgb(0, 150, 136);            /* Color of the scrollbar handle */  \n"
"    min-height: 10px;               /* Minimum height of the handle */  \n"
"    border-radius:2px;\n"
"}  \n"
"QScrollBar::handle:vertical:hover {  \n"
"    background-color: rgb(0, 194, 175);            /* Color of the scrollbar handle */  \n"
"    \n"
"}  \n"
"QScrollBar::handle:vertical:pressed{  \n"
"    background-color:rgb(0, 150, 136);            /* Color of the scrollbar handle */  \n"
"}  \n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:rgb(0, 126, 113);\n"
"    height: 15px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(0, 170, 153);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color:rgb(0, 126, 113);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color:rgb(0, 126, 113);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(0, 170, 153);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color:rgb(0, 126, 113);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"/*                                  */\n"
"\n"
"\n"
"QScrollBar:horizontal {  \n"
"    background-color: rgb(139, 211, 217);            /* Background color */  \n"
"    height: 14px;                   /* Height of the scrollbar */  \n"
"    border: none;  \n"
"    border-radius: 0px;            /* Border styling */  \n"
"}  \n"
"\n"
"QScrollBar::handle:horizontal {  \n"
"    background-color:rgb(0, 150, 136);            /* Color of the scrollbar handle */  \n"
"    min-width: 30px;               /* Minimum width of the handle */  \n"
"    border-radius: 2px;  \n"
"}  \n"
"\n"
"QScrollBar::handle:horizontal:hover {  \n"
"    background-color:  rgb(0, 194, 175);            /* Color of the scrollbar handle when hovered */  \n"
"}  \n"
"\n"
"QScrollBar::handle:horizontal:pressed {  \n"
"    background-color:rgb(0, 150, 136);            /* Color of the scrollbar handle when pressed */  \n"
"}  \n"
"\n"
"/* BTN LEFT - SCROLLBAR */  \n"
"QScrollBar::sub-line:horizontal {  \n"
"    border: none;  \n"
"    background-color: rgb(0, 126, 113);  \n"
"    width: 15px;  \n"
"    border-top-left-radius: 7px;  \n"
"    border-bottom-left-radius: 7px;  \n"
"    subcontrol-position: left;  \n"
"    subcontrol-origin: margin;  \n"
"}  \n"
"\n"
"QScrollBar::sub-line:horizontal:hover {  \n"
"    background-color: rgb(0, 194, 175);  \n"
"}  \n"
"\n"
"QScrollBar::sub-line:horizontal:pressed {  \n"
"    background-color: rgb(0, 126, 113);  \n"
"}  \n"
"\n"
"/* BTN RIGHT - SCROLLBAR */  \n"
"QScrollBar::add-line:horizontal {  \n"
"    border: none;  \n"
"    background-color: rgb(0, 126, 113);  \n"
"    width: 15px;  \n"
"    border-top-right-radius: 7px;  \n"
"    border-bottom-right-radius: 7px;  \n"
"    subcontrol-position: right;  \n"
"    subcontrol-origin: margin;  \n"
"}  \n"
"\n"
"QScrollBar::add-line:horizontal:hover {  \n"
"    background-color: rgb(0, 194, 175);  \n"
"}  \n"
"\n"
"QScrollBar::add-line:horizontal:pressed {  \n"
"    background-color: rgb(0, 126, 113);  \n"
"}  \n"
"\n"
"/* RESET ARROWS */  \n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {  \n"
"    background: none; /* No background for the arrow buttons */  \n"
"}  \n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {  \n"
"    background: none; /* No background for the pages */  \n"
"}")
        self.centralwidget = QtWidgets.QWidget(Form_Crypto)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("background-color: rgb(133, 218, 226);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("QScrollBar:vertical{\n"
"border:none;\n"
"background:rgb(135, 219, 226);\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1222, 1250))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet("\n"
"color:rgb(0, 124, 112);")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1200, 1200))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 170, 1081, 851))
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1081, 851))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line.setGeometry(QtCore.QRect(-10, 50, 1201, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_3.setGeometry(QtCore.QRect(-10, 290, 1201, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.cardano = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents_2)
        self.cardano.setGeometry(QtCore.QRect(0, 320, 101, 48))
        self.cardano.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cardano.setStyleSheet("QPushButton {  \n"
"    \n"
"    background-color:rgb(133, 218, 226);\n"
"    color: rgb(241, 241, 241); /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: rgb(121, 199, 206);\n"
"}  \n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../cryptocurrency-icons-master/32/color/chsb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cardano.setIcon(icon1)
        self.cardano.setObjectName("cardano")
        self.tron = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents_2)
        self.tron.setGeometry(QtCore.QRect(0, 230, 101, 48))
        self.tron.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tron.setStyleSheet("QPushButton {  \n"
"    \n"
"    background-color:rgb(133, 218, 226);\n"
"    color: rgb(241, 241, 241); /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: rgb(121, 199, 206);\n"
"}  \n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../icon/usdt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tron.setIcon(icon2)
        self.tron.setObjectName("tron")
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_5.setGeometry(QtCore.QRect(-10, 210, 1201, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(430, 70, 651, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout4.setObjectName("verticalLayout4")
        self.ethereum = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents_2)
        self.ethereum.setGeometry(QtCore.QRect(0, 70, 101, 48))
        self.ethereum.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ethereum.setStyleSheet("QPushButton {  \n"
"    \n"
"    background-color:rgb(133, 218, 226);\n"
"    color: rgb(241, 241, 241); /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: rgb(121, 199, 206);\n"
"}  \n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../eth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ethereum.setIcon(icon3)
        self.ethereum.setObjectName("ethereum")
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_2.setGeometry(QtCore.QRect(-10, 130, 1201, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tether = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents_2)
        self.tether.setGeometry(QtCore.QRect(0, 150, 101, 48))
        self.tether.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tether.setStyleSheet("QPushButton {  \n"
"    \n"
"    background-color:rgb(133, 218, 226);\n"
"    color: rgb(241, 241, 241); /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: rgb(121, 199, 206);\n"
"}  \n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../icon/tern.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tether.setIcon(icon4)
        self.tether.setObjectName("tether")
        self.label15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label15.setGeometry(QtCore.QRect(200, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label15.setFont(font)
        self.label15.setStyleSheet("color: rgb(0, 76, 68);")
        self.label15.setAlignment(QtCore.Qt.AlignCenter)
        self.label15.setObjectName("label15")
        self.label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label2.setGeometry(QtCore.QRect(110, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setStyleSheet("color: rgb(0, 76, 68);")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.label18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label18.setGeometry(QtCore.QRect(200, 320, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label18.setFont(font)
        self.label18.setStyleSheet("color: rgb(0, 76, 68);")
        self.label18.setAlignment(QtCore.Qt.AlignCenter)
        self.label18.setObjectName("label18")
        self.label3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label3.setGeometry(QtCore.QRect(110, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setStyleSheet("color: rgb(0, 76, 68);")
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName("label3")
        self.label4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label4.setGeometry(QtCore.QRect(110, 240, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setStyleSheet("color: rgb(0, 76, 68);")
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")
        self.label16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label16.setGeometry(QtCore.QRect(220, 160, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label16.setFont(font)
        self.label16.setStyleSheet("color: rgb(0, 76, 68);")
        self.label16.setAlignment(QtCore.Qt.AlignCenter)
        self.label16.setObjectName("label16")
        self.label17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label17.setGeometry(QtCore.QRect(210, 240, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label17.setFont(font)
        self.label17.setStyleSheet("color: rgb(0, 76, 68);")
        self.label17.setAlignment(QtCore.Qt.AlignCenter)
        self.label17.setObjectName("label17")
        self.label5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label5.setGeometry(QtCore.QRect(110, 320, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label5.setFont(font)
        self.label5.setStyleSheet("color: rgb(0, 76, 68);")
        self.label5.setAlignment(QtCore.Qt.AlignCenter)
        self.label5.setObjectName("label5")
        self.label20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label20.setGeometry(QtCore.QRect(190, 480, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label20.setFont(font)
        self.label20.setStyleSheet("color: rgb(0, 76, 68);")
        self.label20.setAlignment(QtCore.Qt.AlignCenter)
        self.label20.setObjectName("label20")
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_4.setGeometry(QtCore.QRect(-10, 530, 1201, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.dogcoin = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents_2)
        self.dogcoin.setGeometry(QtCore.QRect(0, 390, 101, 48))
        self.dogcoin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dogcoin.setStyleSheet("QPushButton {  \n"
"    \n"
"    background-color:rgb(133, 218, 226);\n"
"    color: rgb(241, 241, 241); /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: rgb(121, 199, 206);\n"
"}  \n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../icon/doge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dogcoin.setIcon(icon5)
        self.dogcoin.setObjectName("dogcoin")
        self.label19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label19.setGeometry(QtCore.QRect(190, 400, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label19.setFont(font)
        self.label19.setStyleSheet("color: rgb(0, 76, 68);")
        self.label19.setAlignment(QtCore.Qt.AlignCenter)
        self.label19.setObjectName("label19")
        self.label6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label6.setGeometry(QtCore.QRect(100, 400, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label6.setFont(font)
        self.label6.setStyleSheet("color: rgb(0, 76, 68);")
        self.label6.setAlignment(QtCore.Qt.AlignCenter)
        self.label6.setObjectName("label6")
        self.polkadot = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents_2)
        self.polkadot.setGeometry(QtCore.QRect(0, 470, 101, 48))
        self.polkadot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.polkadot.setStyleSheet("QPushButton {  \n"
"    \n"
"    background-color:rgb(133, 218, 226);\n"
"    color: rgb(241, 241, 241); /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: rgb(121, 199, 206);\n"
"}  \n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../cryptocurrency-icons-master/32/color/poly.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polkadot.setIcon(icon6)
        self.polkadot.setObjectName("polkadot")
        self.label7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label7.setGeometry(QtCore.QRect(110, 480, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label7.setFont(font)
        self.label7.setStyleSheet("color: rgb(0, 76, 68);")
        self.label7.setAlignment(QtCore.Qt.AlignCenter)
        self.label7.setObjectName("label7")
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_6.setGeometry(QtCore.QRect(0, 450, 1201, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(430, 150, 651, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout5.setObjectName("verticalLayout5")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(430, 230, 651, 51))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout6.setObjectName("verticalLayout6")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(430, 310, 651, 51))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout7.setObjectName("verticalLayout7")
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_9.setGeometry(QtCore.QRect(0, 370, 1201, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(430, 390, 651, 51))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout8.setObjectName("verticalLayout8")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(430, 470, 651, 51))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout9.setObjectName("verticalLayout9")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(430, 550, 651, 51))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout10.setObjectName("verticalLayout10")
        self.stellar = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents_2)
        self.stellar.setGeometry(QtCore.QRect(0, 630, 111, 48))
        self.stellar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stellar.setStyleSheet("QPushButton {  \n"
"    \n"
"    background-color:rgb(133, 218, 226);\n"
"    color: rgb(241, 241, 241); /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: rgb(121, 199, 206);\n"
"}  \n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../cryptocurrency-icons-master/32/color/strat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stellar.setIcon(icon7)
        self.stellar.setObjectName("stellar")
        self.label9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label9.setGeometry(QtCore.QRect(110, 640, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label9.setFont(font)
        self.label9.setStyleSheet("color: rgb(0, 76, 68);")
        self.label9.setAlignment(QtCore.Qt.AlignCenter)
        self.label9.setObjectName("label9")
        self.label22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label22.setGeometry(QtCore.QRect(200, 640, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label22.setFont(font)
        self.label22.setStyleSheet("color: rgb(0, 76, 68);")
        self.label22.setAlignment(QtCore.Qt.AlignCenter)
        self.label22.setObjectName("label22")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(430, 630, 651, 51))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout11.setObjectName("verticalLayout11")
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_7.setGeometry(QtCore.QRect(0, 610, 1201, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label10.setGeometry(QtCore.QRect(110, 730, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label10.setFont(font)
        self.label10.setStyleSheet("color: rgb(0, 76, 68);")
        self.label10.setAlignment(QtCore.Qt.AlignCenter)
        self.label10.setObjectName("label10")
        self.label23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label23.setGeometry(QtCore.QRect(200, 730, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label23.setFont(font)
        self.label23.setStyleSheet("color: rgb(0, 76, 68);")
        self.label23.setAlignment(QtCore.Qt.AlignCenter)
        self.label23.setObjectName("label23")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(430, 720, 651, 51))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout12.setObjectName("verticalLayout12")
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_8.setGeometry(QtCore.QRect(0, 690, 1201, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.litecoin = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents_2)
        self.litecoin.setGeometry(QtCore.QRect(0, 720, 111, 48))
        self.litecoin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.litecoin.setStyleSheet("QPushButton {  \n"
"    \n"
"    background-color:rgb(133, 218, 226);\n"
"    color: rgb(241, 241, 241); /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: rgb(121, 199, 206);\n"
"}  \n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../cryptocurrency-icons-master/32/color/ltc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.litecoin.setIcon(icon8)
        self.litecoin.setObjectName("litecoin")
        self.label11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label11.setGeometry(QtCore.QRect(110, 810, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label11.setFont(font)
        self.label11.setStyleSheet("color: rgb(0, 76, 68);")
        self.label11.setAlignment(QtCore.Qt.AlignCenter)
        self.label11.setObjectName("label11")
        self.label24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label24.setGeometry(QtCore.QRect(200, 810, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label24.setFont(font)
        self.label24.setStyleSheet("color: rgb(0, 76, 68);")
        self.label24.setAlignment(QtCore.Qt.AlignCenter)
        self.label24.setObjectName("label24")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(430, 800, 651, 51))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout13.setObjectName("verticalLayout13")
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_10.setGeometry(QtCore.QRect(0, 780, 1201, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.uniswap = QtWidgets.QCommandLinkButton(self.scrollAreaWidgetContents_2)
        self.uniswap.setGeometry(QtCore.QRect(0, 810, 111, 48))
        self.uniswap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uniswap.setStyleSheet("QPushButton {  \n"
"    \n"
"    background-color:rgb(133, 218, 226);\n"
"    color: rgb(241, 241, 241); /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: rgb(121, 199, 206);\n"
"}  \n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../cryptocurrency-icons-master/32/color/uni.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uniswap.setIcon(icon9)
        self.uniswap.setObjectName("uniswap")
        self.label33 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label33.setGeometry(QtCore.QRect(290, 480, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label33.setFont(font)
        self.label33.setStyleSheet("color: rgb(0, 76, 68);")
        self.label33.setAlignment(QtCore.Qt.AlignCenter)
        self.label33.setObjectName("label33")
        self.label36 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label36.setGeometry(QtCore.QRect(300, 730, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label36.setFont(font)
        self.label36.setStyleSheet("color: rgb(0, 76, 68);")
        self.label36.setAlignment(QtCore.Qt.AlignCenter)
        self.label36.setObjectName("label36")
        self.label32 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label32.setGeometry(QtCore.QRect(290, 400, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label32.setFont(font)
        self.label32.setStyleSheet("color: rgb(0, 76, 68);")
        self.label32.setAlignment(QtCore.Qt.AlignCenter)
        self.label32.setObjectName("label32")
        self.label28 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label28.setGeometry(QtCore.QRect(300, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label28.setFont(font)
        self.label28.setStyleSheet("color: rgb(0, 76, 68);")
        self.label28.setAlignment(QtCore.Qt.AlignCenter)
        self.label28.setObjectName("label28")
        self.label34 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label34.setGeometry(QtCore.QRect(290, 560, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label34.setFont(font)
        self.label34.setStyleSheet("color: rgb(0, 76, 68);")
        self.label34.setAlignment(QtCore.Qt.AlignCenter)
        self.label34.setObjectName("label34")
        self.label35 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label35.setGeometry(QtCore.QRect(290, 640, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label35.setFont(font)
        self.label35.setStyleSheet("color: rgb(0, 76, 68);")
        self.label35.setAlignment(QtCore.Qt.AlignCenter)
        self.label35.setObjectName("label35")
        self.label29 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label29.setGeometry(QtCore.QRect(320, 160, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label29.setFont(font)
        self.label29.setStyleSheet("color: rgb(0, 76, 68);")
        self.label29.setAlignment(QtCore.Qt.AlignCenter)
        self.label29.setObjectName("label29")
        self.label30 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label30.setGeometry(QtCore.QRect(310, 240, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label30.setFont(font)
        self.label30.setStyleSheet("color: rgb(0, 76, 68);")
        self.label30.setAlignment(QtCore.Qt.AlignCenter)
        self.label30.setObjectName("label30")
        self.label31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label31.setGeometry(QtCore.QRect(310, 320, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label31.setFont(font)
        self.label31.setStyleSheet("color: rgb(0, 76, 68);")
        self.label31.setAlignment(QtCore.Qt.AlignCenter)
        self.label31.setObjectName("label31")
        self.label37 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label37.setGeometry(QtCore.QRect(290, 810, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label37.setFont(font)
        self.label37.setStyleSheet("color: rgb(0, 76, 68);")
        self.label37.setAlignment(QtCore.Qt.AlignCenter)
        self.label37.setObjectName("label37")
        self.label21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label21.setGeometry(QtCore.QRect(190, 560, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label21.setFont(font)
        self.label21.setStyleSheet("color: rgb(0, 76, 68);")
        self.label21.setAlignment(QtCore.Qt.AlignCenter)
        self.label21.setObjectName("label21")
        self.label_80 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_80.setGeometry(QtCore.QRect(670, 20, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_80.setFont(font)
        self.label_80.setStyleSheet("\n"
"color:rgb(255, 255, 255);")
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_81 = QtWidgets.QLabel(self.frame)
        self.label_81.setGeometry(QtCore.QRect(120, 190, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_81.setFont(font)
        self.label_81.setStyleSheet("\n"
"color:rgb(255, 255, 255);")
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.label_90 = QtWidgets.QLabel(self.frame)
        self.label_90.setGeometry(QtCore.QRect(210, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_90.setFont(font)
        self.label_90.setStyleSheet("\n"
"color:rgb(255, 255, 255);")
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setObjectName("label_90")
        self.label8 = QtWidgets.QLabel(self.frame)
        self.label8.setGeometry(QtCore.QRect(110, 730, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label8.setFont(font)
        self.label8.setStyleSheet("color: rgb(0, 76, 68);")
        self.label8.setAlignment(QtCore.Qt.AlignCenter)
        self.label8.setObjectName("label8")
        self.sui = QtWidgets.QCommandLinkButton(self.frame)
        self.sui.setGeometry(QtCore.QRect(0, 720, 111, 48))
        self.sui.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sui.setStyleSheet("QPushButton {  \n"
"    \n"
"    background-color:rgb(133, 218, 226);\n"
"    color: rgb(241, 241, 241); /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: rgb(121, 199, 206);\n"
"}  \n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../cryptocurrency-icons-master/32/color/soc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sui.setIcon(icon10)
        self.sui.setObjectName("sui")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(530, 1190, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(0, 76, 68);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(430, 1060, 651, 51))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout14.setObjectName("verticalLayout14")
        self.label25 = QtWidgets.QLabel(self.frame)
        self.label25.setGeometry(QtCore.QRect(190, 1070, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label25.setFont(font)
        self.label25.setStyleSheet("color: rgb(0, 76, 68);")
        self.label25.setAlignment(QtCore.Qt.AlignCenter)
        self.label25.setObjectName("label25")
        self.label12 = QtWidgets.QLabel(self.frame)
        self.label12.setGeometry(QtCore.QRect(110, 1070, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label12.setFont(font)
        self.label12.setStyleSheet("color: rgb(0, 76, 68);")
        self.label12.setAlignment(QtCore.Qt.AlignCenter)
        self.label12.setObjectName("label12")
        self.pepe = QtWidgets.QCommandLinkButton(self.frame)
        self.pepe.setGeometry(QtCore.QRect(0, 1060, 111, 48))
        self.pepe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pepe.setStyleSheet("QPushButton {  \n"
"    \n"
"    background-color:rgb(133, 218, 226);\n"
"    color: rgb(241, 241, 241); /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: rgb(121, 199, 206);\n"
"}  \n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../cryptocurrency-icons-master/32/color/pre.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pepe.setIcon(icon11)
        self.pepe.setObjectName("pepe")
        self.line_12 = QtWidgets.QFrame(self.frame)
        self.line_12.setGeometry(QtCore.QRect(0, 1120, 1201, 16))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.aptes = QtWidgets.QCommandLinkButton(self.frame)
        self.aptes.setGeometry(QtCore.QRect(0, 1150, 111, 48))
        self.aptes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aptes.setStyleSheet("QPushButton {  \n"
"    \n"
"    background-color:rgb(133, 218, 226);\n"
"    color: rgb(241, 241, 241); /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: rgb(121, 199, 206);\n"
"}  \n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../cryptocurrency-icons-master/32/color/ape.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aptes.setIcon(icon12)
        self.aptes.setObjectName("aptes")
        self.label13 = QtWidgets.QLabel(self.frame)
        self.label13.setGeometry(QtCore.QRect(110, 1150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label13.setFont(font)
        self.label13.setStyleSheet("color: rgb(0, 76, 68);")
        self.label13.setAlignment(QtCore.Qt.AlignCenter)
        self.label13.setObjectName("label13")
        self.label26 = QtWidgets.QLabel(self.frame)
        self.label26.setGeometry(QtCore.QRect(190, 1150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label26.setFont(font)
        self.label26.setStyleSheet("color: rgb(0, 76, 68);")
        self.label26.setAlignment(QtCore.Qt.AlignCenter)
        self.label26.setObjectName("label26")
        self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(430, 1140, 651, 51))
        self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
        self.verticalLayout15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout15.setObjectName("verticalLayout15")
        self.label38 = QtWidgets.QLabel(self.frame)
        self.label38.setGeometry(QtCore.QRect(290, 1070, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label38.setFont(font)
        self.label38.setStyleSheet("color: rgb(0, 76, 68);")
        self.label38.setAlignment(QtCore.Qt.AlignCenter)
        self.label38.setObjectName("label38")
        self.label39 = QtWidgets.QLabel(self.frame)
        self.label39.setGeometry(QtCore.QRect(290, 1150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label39.setFont(font)
        self.label39.setStyleSheet("color: rgb(0, 76, 68);")
        self.label39.setAlignment(QtCore.Qt.AlignCenter)
        self.label39.setObjectName("label39")
        self.label_91 = QtWidgets.QLabel(self.frame)
        self.label_91.setGeometry(QtCore.QRect(310, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_91.setFont(font)
        self.label_91.setStyleSheet("\n"
"color:rgb(255, 255, 255);")
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.line_11 = QtWidgets.QFrame(self.frame)
        self.line_11.setGeometry(QtCore.QRect(-20, 1040, 1201, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_82 = QtWidgets.QLabel(self.frame)
        self.label_82.setGeometry(QtCore.QRect(10, 190, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_82.setFont(font)
        self.label_82.setStyleSheet("\n"
"color:rgb(255, 255, 255);")
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 0, 961, 161))
        self.frame_2.setStyleSheet("background-color: rgb(0, 129, 0);\n"
"/*background-color: rgb(76, 126, 130);\n"
"background-color: rgb(47, 82, 223);*/\n"
"background-color: rgb(0, 124, 112);\n"
"border: none; /* No border */  \n"
"padding: 10px;  \n"
"border-radius: 10px; /* Rounded corners */  ")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.bitcoin = QtWidgets.QCommandLinkButton(self.frame_2)
        self.bitcoin.setGeometry(QtCore.QRect(10, 60, 91, 48))
        self.bitcoin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bitcoin.setStyleSheet("QPushButton {  \n"
"    \n"
"    /*background-color:rgb(133, 218, 226);*/\n"
"    \n"
"    /*background-color: rgb(0, 129, 0);*/\n"
"    \n"
"    background-color: rgb(0, 124, 112);\n"
"    color: rgb(241, 241, 241); /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    \n"
"    background-color: rgb(0, 152, 137);\n"
"    /*background-color: rgb(0, 156, 0);*/\n"
"    /*background-color: rgb(121, 199, 206);*/\n"
"}  \n"
"")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../btg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bitcoin.setIcon(icon13)
        self.bitcoin.setObjectName("bitcoin")
        self.label1 = QtWidgets.QLabel(self.frame_2)
        self.label1.setGeometry(QtCore.QRect(130, 30, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color: rgb(0, 76, 68);")
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.label14 = QtWidgets.QLabel(self.frame_2)
        self.label14.setGeometry(QtCore.QRect(120, 70, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label14.setFont(font)
        self.label14.setStyleSheet("color: rgb(0, 76, 68);")
        self.label14.setAlignment(QtCore.Qt.AlignCenter)
        self.label14.setObjectName("label14")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 20, 681, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout3.setObjectName("verticalLayout3")
        self.label27 = QtWidgets.QLabel(self.frame_2)
        self.label27.setGeometry(QtCore.QRect(120, 110, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label27.setFont(font)
        self.label27.setStyleSheet("color: rgb(0, 76, 68);")
        self.label27.setAlignment(QtCore.Qt.AlignCenter)
        self.label27.setObjectName("label27")
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        Form_Crypto.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Form_Crypto)
        self.statusbar.setObjectName("statusbar")
        Form_Crypto.setStatusBar(self.statusbar)

        self.retranslateUi(Form_Crypto)
        QtCore.QMetaObject.connectSlotsByName(Form_Crypto)

    def retranslateUi(self, Form_Crypto):
        _translate = QtCore.QCoreApplication.translate
        Form_Crypto.setWindowTitle(_translate("Form_Crypto", "cryptocurrency"))
        self.label_15.setText(_translate("Form_Crypto", "Wellcome user"))
        self.cardano.setText(_translate("Form_Crypto", "Cardano"))
        self.tron.setText(_translate("Form_Crypto", "Tron"))
        self.ethereum.setText(_translate("Form_Crypto", "Ethereum"))
        self.tether.setText(_translate("Form_Crypto", "Tether"))
        self.label15.setText(_translate("Form_Crypto", "TextLabel"))
        self.label2.setText(_translate("Form_Crypto", "TextLabel"))
        self.label18.setText(_translate("Form_Crypto", "TextLabel"))
        self.label3.setText(_translate("Form_Crypto", "TextLabel"))
        self.label4.setText(_translate("Form_Crypto", "TextLabel"))
        self.label16.setText(_translate("Form_Crypto", "TextLabel"))
        self.label17.setText(_translate("Form_Crypto", "TextLabel"))
        self.label5.setText(_translate("Form_Crypto", "TextLabel"))
        self.label20.setText(_translate("Form_Crypto", "TextLabel"))
        self.dogcoin.setText(_translate("Form_Crypto", "Dogcoin"))
        self.label19.setText(_translate("Form_Crypto", "TextLabel"))
        self.label6.setText(_translate("Form_Crypto", "TextLabel"))
        self.polkadot.setText(_translate("Form_Crypto", "Polkadot"))
        self.label7.setText(_translate("Form_Crypto", "TextLabel"))
        self.stellar.setText(_translate("Form_Crypto", "Stellar"))
        self.label9.setText(_translate("Form_Crypto", "TextLabel"))
        self.label22.setText(_translate("Form_Crypto", "TextLabel"))
        self.label10.setText(_translate("Form_Crypto", "TextLabel"))
        self.label23.setText(_translate("Form_Crypto", "TextLabel"))
        self.litecoin.setText(_translate("Form_Crypto", "Litecoin"))
        self.label11.setText(_translate("Form_Crypto", "TextLabel"))
        self.label24.setText(_translate("Form_Crypto", "TextLabel"))
        self.uniswap.setText(_translate("Form_Crypto", "Uniswap"))
        self.label33.setText(_translate("Form_Crypto", "TextLabel"))
        self.label36.setText(_translate("Form_Crypto", "TextLabel"))
        self.label32.setText(_translate("Form_Crypto", "TextLabel"))
        self.label28.setText(_translate("Form_Crypto", "TextLabel"))
        self.label34.setText(_translate("Form_Crypto", "TextLabel"))
        self.label35.setText(_translate("Form_Crypto", "TextLabel"))
        self.label29.setText(_translate("Form_Crypto", "TextLabel"))
        self.label30.setText(_translate("Form_Crypto", "TextLabel"))
        self.label31.setText(_translate("Form_Crypto", "TextLabel"))
        self.label37.setText(_translate("Form_Crypto", "TextLabel"))
        self.label21.setText(_translate("Form_Crypto", "TextLabel"))
        self.label_80.setText(_translate("Form_Crypto", "Price Over Time"))
        self.label_81.setText(_translate("Form_Crypto", "Price"))
        self.label_90.setText(_translate("Form_Crypto", "Market Cap"))
        self.label8.setText(_translate("Form_Crypto", "TextLabel"))
        self.sui.setText(_translate("Form_Crypto", "Sui"))
        self.label_21.setText(_translate("Form_Crypto", "TextLabel"))
        self.label25.setText(_translate("Form_Crypto", "TextLabel"))
        self.label12.setText(_translate("Form_Crypto", "TextLabel"))
        self.pepe.setText(_translate("Form_Crypto", "Pepe"))
        self.aptes.setText(_translate("Form_Crypto", "Aptes"))
        self.label13.setText(_translate("Form_Crypto", "TextLabel"))
        self.label26.setText(_translate("Form_Crypto", "TextLabel"))
        self.label38.setText(_translate("Form_Crypto", "TextLabel"))
        self.label39.setText(_translate("Form_Crypto", "TextLabel"))
        self.label_91.setText(_translate("Form_Crypto", "24h volume"))
        self.label_82.setText(_translate("Form_Crypto", "Token List"))
        self.bitcoin.setText(_translate("Form_Crypto", "Bitcoin"))
        self.label1.setText(_translate("Form_Crypto", "<html><head/><body><p><span style=\" font-size:11pt;\">TextLabel</span></p></body></html>"))
        self.label14.setText(_translate("Form_Crypto", "TextLabel"))
        self.label27.setText(_translate("Form_Crypto", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Crypto = QtWidgets.QMainWindow()
    ui = Ui_Form_Crypto()
    ui.setupUi(Form_Crypto)
    Form_Crypto.show()
    sys.exit(app.exec_())
