# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Log_In(object):
    def setupUi(self, Log_In):
        Log_In.setObjectName("Log_In")
        Log_In.resize(650, 332)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../icon/gno.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Log_In.setWindowIcon(icon)
        Log_In.setStyleSheet("QWidget {  \n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,   \n"
"                                 stop:0 #7ed8e0, stop:1 #e0f7fa);  \n"
"    color: #333;  \n"
"    font-family: Arial, sans-serif;  \n"
"}  ")
        self.centralwidget = QtWidgets.QWidget(Log_In)
        self.centralwidget.setObjectName("centralwidget")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(110, 180, 521, 41))
        self.login.setStyleSheet("QPushButton {  \n"
"    background-color: #009688; /* Teal */  \n"
"    color: white; /* White text */  \n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"QPushButton:hover {  \n"
"    background-color: #00796b; /* Darker teal on hover */  \n"
"}  ")
        self.login.setObjectName("login")
        self.emailadd = QtWidgets.QLineEdit(self.centralwidget)
        self.emailadd.setGeometry(QtCore.QRect(110, 60, 521, 51))
        self.emailadd.setStyleSheet("QLineEdit {  \n"
"    border: 2px solid #00796b; /* Border color */  \n"
"    border-radius: 10px;  \n"
"    padding: 10px;  \n"
"    font-size: 16px; /* Text size */  \n"
"    background-color: #ffffff; /* White background */  \n"
"}  ")
        self.emailadd.setObjectName("emailadd")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(110, 120, 521, 51))
        self.password.setStyleSheet("QLineEdit {  \n"
"    border: 2px solid #00796b; /* Border color */  \n"
"    border-radius: 10px;  \n"
"    padding: 10px;  \n"
"    font-size: 16px; /* Text size */  \n"
"    background-color: #ffffff; /* White background */  \n"
"}  ")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(29, 89, 255);\n"
"background-color: transparent;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(29, 89, 255);\n"
"background-color: transparent;")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(29, 89, 255);\n"
"background-color: transparent;")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 240, 141, 21))
        self.label_3.setStyleSheet("background-color:transparent;")
        self.label_3.setObjectName("label_3")
        self.createuser = QtWidgets.QPushButton(self.centralwidget)
        self.createuser.setGeometry(QtCore.QRect(370, 230, 81, 41))
        self.createuser.setStyleSheet("QPushButton {  \n"
"    background-color:transparent; /* Teal */  \n"
"    \n"
"    color: rgb(0, 115, 101);\n"
"    border: none; /* No border */  \n"
"    padding: 10px;  \n"
"    border-radius: 10px; /* Rounded corners */  \n"
"}  \n"
"\n"
"")
        self.createuser.setObjectName("createuser")
        Log_In.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Log_In)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 23))
        self.menubar.setObjectName("menubar")
        Log_In.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Log_In)
        self.statusbar.setObjectName("statusbar")
        Log_In.setStatusBar(self.statusbar)

        self.retranslateUi(Log_In)
        QtCore.QMetaObject.connectSlotsByName(Log_In)

    def retranslateUi(self, Log_In):
        _translate = QtCore.QCoreApplication.translate
        Log_In.setWindowTitle(_translate("Log_In", "log in"))
        self.login.setText(_translate("Log_In", "log in"))
        self.label.setText(_translate("Log_In", "Let\'s Sign In"))
        self.label_2.setText(_translate("Log_In", "Eamil Address"))
        self.label_4.setText(_translate("Log_In", "Password"))
        self.label_3.setText(_translate("Log_In", "Don\'t have an account?"))
        self.createuser.setText(_translate("Log_In", "Sign up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Log_In = QtWidgets.QMainWindow()
    ui = Ui_Log_In()
    ui.setupUi(Log_In)
    Log_In.show()
    sys.exit(app.exec_())
