# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub_form_crypto.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sub_form_crypto(object):
    def setupUi(self, sub_form_crypto):
        sub_form_crypto.setObjectName("sub_form_crypto")
        sub_form_crypto.resize(524, 814)
        sub_form_crypto.setStyleSheet("QWidget {  \n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,   \n"
"                                 stop:0 #7ed8e0, stop:1 #e0f7fa);  \n"
"    color: #333;  \n"
"    font-family: Arial, sans-serif;  \n"
"}  ")
        self.centralwidget = QtWidgets.QWidget(sub_form_crypto)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 180, 501, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 50, 501, 121))
        self.frame.setStyleSheet("background-color: rgb(109, 176, 165);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.volume = QtWidgets.QLabel(self.frame)
        self.volume.setGeometry(QtCore.QRect(10, 60, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.volume.setFont(font)
        self.volume.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.volume.setObjectName("volume")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 510, 501, 251))
        self.frame_2.setStyleSheet("background-color: rgb(109, 176, 165);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.aed = QtWidgets.QLabel(self.frame_2)
        self.aed.setGeometry(QtCore.QRect(10, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.aed.setFont(font)
        self.aed.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.aed.setObjectName("aed")
        self.ars = QtWidgets.QLabel(self.frame_2)
        self.ars.setGeometry(QtCore.QRect(10, 50, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.ars.setFont(font)
        self.ars.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.ars.setObjectName("ars")
        self.aud = QtWidgets.QLabel(self.frame_2)
        self.aud.setGeometry(QtCore.QRect(10, 90, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.aud.setFont(font)
        self.aud.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.aud.setObjectName("aud")
        self.aud1 = QtWidgets.QLabel(self.frame_2)
        self.aud1.setGeometry(QtCore.QRect(100, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.aud1.setFont(font)
        self.aud1.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.aud1.setObjectName("aud1")
        self.aed1 = QtWidgets.QLabel(self.frame_2)
        self.aed1.setGeometry(QtCore.QRect(100, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.aed1.setFont(font)
        self.aed1.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.aed1.setObjectName("aed1")
        self.ars1 = QtWidgets.QLabel(self.frame_2)
        self.ars1.setGeometry(QtCore.QRect(100, 50, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.ars1.setFont(font)
        self.ars1.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.ars1.setObjectName("ars1")
        self.bdt = QtWidgets.QLabel(self.frame_2)
        self.bdt.setGeometry(QtCore.QRect(10, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.bdt.setFont(font)
        self.bdt.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.bdt.setObjectName("bdt")
        self.bhd = QtWidgets.QLabel(self.frame_2)
        self.bhd.setGeometry(QtCore.QRect(10, 210, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.bhd.setFont(font)
        self.bhd.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.bhd.setObjectName("bhd")
        self.bdt1 = QtWidgets.QLabel(self.frame_2)
        self.bdt1.setGeometry(QtCore.QRect(100, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.bdt1.setFont(font)
        self.bdt1.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.bdt1.setObjectName("bdt1")
        self.bhd1 = QtWidgets.QLabel(self.frame_2)
        self.bhd1.setGeometry(QtCore.QRect(100, 210, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.bhd1.setFont(font)
        self.bhd1.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.bhd1.setObjectName("bhd1")
        self.bch1 = QtWidgets.QLabel(self.frame_2)
        self.bch1.setGeometry(QtCore.QRect(100, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.bch1.setFont(font)
        self.bch1.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.bch1.setObjectName("bch1")
        self.bch = QtWidgets.QLabel(self.frame_2)
        self.bch.setGeometry(QtCore.QRect(10, 130, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.bch.setFont(font)
        self.bch.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.bch.setObjectName("bch")
        self.bnb = QtWidgets.QLabel(self.frame_2)
        self.bnb.setGeometry(QtCore.QRect(260, 50, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.bnb.setFont(font)
        self.bnb.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.bnb.setObjectName("bnb")
        self.brl = QtWidgets.QLabel(self.frame_2)
        self.brl.setGeometry(QtCore.QRect(260, 90, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.brl.setFont(font)
        self.brl.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.brl.setObjectName("brl")
        self.bnb1 = QtWidgets.QLabel(self.frame_2)
        self.bnb1.setGeometry(QtCore.QRect(320, 50, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.bnb1.setFont(font)
        self.bnb1.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.bnb1.setObjectName("bnb1")
        self.brl1 = QtWidgets.QLabel(self.frame_2)
        self.brl1.setGeometry(QtCore.QRect(320, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.brl1.setFont(font)
        self.brl1.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.brl1.setObjectName("brl1")
        self.bmd1 = QtWidgets.QLabel(self.frame_2)
        self.bmd1.setGeometry(QtCore.QRect(320, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.bmd1.setFont(font)
        self.bmd1.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.bmd1.setObjectName("bmd1")
        self.bmd = QtWidgets.QLabel(self.frame_2)
        self.bmd.setGeometry(QtCore.QRect(260, 10, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.bmd.setFont(font)
        self.bmd.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.bmd.setObjectName("bmd")
        self.cad = QtWidgets.QLabel(self.frame_2)
        self.cad.setGeometry(QtCore.QRect(260, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.cad.setFont(font)
        self.cad.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.cad.setObjectName("cad")
        self.chf = QtWidgets.QLabel(self.frame_2)
        self.chf.setGeometry(QtCore.QRect(260, 210, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.chf.setFont(font)
        self.chf.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.chf.setObjectName("chf")
        self.cad1 = QtWidgets.QLabel(self.frame_2)
        self.cad1.setGeometry(QtCore.QRect(320, 170, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.cad1.setFont(font)
        self.cad1.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.cad1.setObjectName("cad1")
        self.chf1 = QtWidgets.QLabel(self.frame_2)
        self.chf1.setGeometry(QtCore.QRect(320, 210, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.chf1.setFont(font)
        self.chf1.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.chf1.setObjectName("chf1")
        self.btc1 = QtWidgets.QLabel(self.frame_2)
        self.btc1.setGeometry(QtCore.QRect(320, 130, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.btc1.setFont(font)
        self.btc1.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.btc1.setObjectName("btc1")
        self.btc = QtWidgets.QLabel(self.frame_2)
        self.btc.setGeometry(QtCore.QRect(260, 130, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        self.btc.setFont(font)
        self.btc.setStyleSheet("background-color:transparent;\n"
"color: rgb(29, 89, 255);\n"
"color: rgb(0, 0, 0);")
        self.btc.setObjectName("btc")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(10, 10, 131, 41))
        self.commandLinkButton.setStyleSheet("background-color: rgb(109, 176, 165);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../icon/icn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon)
        self.commandLinkButton.setObjectName("commandLinkButton")
        sub_form_crypto.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(sub_form_crypto)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 23))
        self.menubar.setObjectName("menubar")
        sub_form_crypto.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sub_form_crypto)
        self.statusbar.setObjectName("statusbar")
        sub_form_crypto.setStatusBar(self.statusbar)

        self.retranslateUi(sub_form_crypto)
        QtCore.QMetaObject.connectSlotsByName(sub_form_crypto)

    def retranslateUi(self, sub_form_crypto):
        _translate = QtCore.QCoreApplication.translate
        sub_form_crypto.setWindowTitle(_translate("sub_form_crypto", "MainWindow"))
        self.label_5.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:12pt;\">Price:</span></p></body></html>"))
        self.volume.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:16pt;\">0000</span></p></body></html>"))
        self.aed.setText(_translate("sub_form_crypto", "AED"))
        self.ars.setText(_translate("sub_form_crypto", "ARS"))
        self.aud.setText(_translate("sub_form_crypto", "AUD"))
        self.aud1.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:9pt;\">000</span></p></body></html>"))
        self.aed1.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:9pt;\">000</span></p></body></html>"))
        self.ars1.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:9pt;\">000</span></p></body></html>"))
        self.bdt.setText(_translate("sub_form_crypto", "BDT"))
        self.bhd.setText(_translate("sub_form_crypto", "BHD"))
        self.bdt1.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:9pt;\">000</span></p></body></html>"))
        self.bhd1.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:9pt;\">000</span></p></body></html>"))
        self.bch1.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:9pt;\">000</span></p></body></html>"))
        self.bch.setText(_translate("sub_form_crypto", "BCH"))
        self.bnb.setText(_translate("sub_form_crypto", "BNB"))
        self.brl.setText(_translate("sub_form_crypto", "BRL"))
        self.bnb1.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:9pt;\">000</span></p></body></html>"))
        self.brl1.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:9pt;\">000</span></p></body></html>"))
        self.bmd1.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:9pt;\">000</span></p></body></html>"))
        self.bmd.setText(_translate("sub_form_crypto", "BMD"))
        self.cad.setText(_translate("sub_form_crypto", "CAD"))
        self.chf.setText(_translate("sub_form_crypto", "CHF"))
        self.cad1.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:9pt;\">000</span></p></body></html>"))
        self.chf1.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:9pt;\">000</span></p></body></html>"))
        self.btc1.setText(_translate("sub_form_crypto", "<html><head/><body><p><span style=\" font-size:9pt;\">000</span></p></body></html>"))
        self.btc.setText(_translate("sub_form_crypto", "BTC"))
        self.commandLinkButton.setText(_translate("sub_form_crypto", "etherum"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sub_form_crypto = QtWidgets.QMainWindow()
    ui = Ui_sub_form_crypto()
    ui.setupUi(sub_form_crypto)
    sub_form_crypto.show()
    sys.exit(app.exec_())
